"""Owner-scoped performance test configuration and results UI."""

from fastapi import APIRouter, Form, Request
from fastapi.responses import RedirectResponse
from sqlalchemy import select, text
from sqlalchemy.orm import Session

from app.automated_runner import validate_target_url
from app.jobs import enqueue_performance_run, request_run_cancellation
from app.main import csrf_token, csrf_valid, current_user, engine, esc, layout
from app.performance_testing import GENERATOR_VERSION, K6Config, generate_k6_script, k6_available
from app.quality_models import PerformanceTestArtifact, utc_now

router = APIRouter()


def _owned_project(db, public_id: str, owner_user_id: int):
    return db.execute(text("""
        SELECT id, name FROM projects WHERE public_id = :public_id
          AND owner_user_id = :owner_user_id AND deleted_at IS NULL
    """), {"public_id": public_id, "owner_user_id": owner_user_id}).mappings().first()


@router.get("/projects/{public_id}/performance")
def performance_page(request: Request, public_id: str):
    user = current_user(request)
    if not user:
        return RedirectResponse("/login", status_code=303)
    with Session(engine) as db:
        project = _owned_project(db, public_id, user.id)
        if not project:
            return RedirectResponse("/projects", status_code=303)
        artifacts = db.execute(text("""
            SELECT a.public_id, a.test_run_id, a.target_url, a.script_sha256,
                   a.script_text, a.configuration_json, a.created_at, r.status
            FROM performance_test_artifacts a
            JOIN quality_test_runs r ON r.id = a.test_run_id
            WHERE a.project_id = :project_id AND a.owner_user_id = :owner
            ORDER BY a.created_at DESC LIMIT 10
        """), {"project_id": project["id"], "owner": user.id}).mappings().all()
        results = db.execute(text("""
            SELECT requests, errors, error_rate, requests_per_second,
                   duration_p50_ms, duration_p90_ms, duration_p95_ms,
                   duration_p99_ms, tool_version, completed_at
            FROM performance_test_results
            WHERE project_id = :project_id AND owner_user_id = :owner
            ORDER BY created_at DESC LIMIT 10
        """), {"project_id": project["id"], "owner": user.id}).mappings().all()
    artifact_html = "".join(
        f"<article><strong>{esc(item['status'])}</strong> · {esc(item['target_url'])}"
        f"<br><small>SHA-256 {esc(item['script_sha256'])}</small>"
        f"<details><summary>Inspect generated k6 script</summary><pre>{esc(item['script_text'])}</pre></details>"
        f"<form method='post' action='/projects/{esc(public_id)}/performance/{item['test_run_id']}/cancel'>"
        f"<input type='hidden' name='csrf' value='{esc(csrf_token(request))}'><button type='submit'>Cancel</button></form></article>"
        for item in artifacts
    ) or "<p>No performance scripts generated yet.</p>"
    result_rows = "".join(
        f"<tr><td>{item['requests']}</td><td>{item['errors']}</td><td>{item['requests_per_second']:.2f}</td>"
        f"<td>{item['duration_p50_ms']:.2f}</td><td>{item['duration_p90_ms']:.2f}</td>"
        f"<td>{item['duration_p95_ms']:.2f}</td><td>{item['duration_p99_ms']:.2f}</td></tr>"
        for item in results
    ) or "<tr><td colspan='7'>No completed performance results yet.</td></tr>"
    content = f"""
    <section class="dashboard-shell"><a href="/projects/{esc(public_id)}">← Project overview</a>
    <h1>Performance tests · {esc(project['name'])}</h1>
    <p>k6 worker: {'available' if k6_available() else 'not installed'}. Only parameter-free GET and HEAD routes are generated by default.</p>
    <form method="post" action="/projects/{esc(public_id)}/performance/run">
      <input type="hidden" name="csrf" value="{esc(csrf_token(request))}">
      <label>Public HTTPS base URL <input name="target_url" type="url" required placeholder="https://staging.example.com"></label>
      <label>Virtual users <input name="vus" type="number" min="1" max="1000" value="1" required></label>
      <label>Duration seconds <input name="duration_seconds" type="number" min="1" max="86400" value="10" required></label>
      <label>Timeout seconds <input name="timeout_seconds" type="number" min="1" max="90000" value="60" required></label>
      <label><input name="authorization_confirmed" type="checkbox" value="yes" required> I confirm I own or have explicit permission to load-test this target.</label>
      <button class="primary-button" type="submit">Generate and queue k6 test</button>
    </form><h2>Generated artifacts</h2>{artifact_html}
    <h2>Exact k6 metrics</h2><table><thead><tr><th>Requests</th><th>Errors</th><th>RPS</th><th>p50 ms</th><th>p90 ms</th><th>p95 ms</th><th>p99 ms</th></tr></thead><tbody>{result_rows}</tbody></table></section>
    """
    return layout("Performance tests", content, request, public=False)


@router.post("/projects/{public_id}/performance/run")
def queue_performance_test(
    request: Request, public_id: str, csrf: str = Form(...),
    target_url: str = Form(...), vus: int = Form(...),
    duration_seconds: int = Form(...), timeout_seconds: int = Form(...),
    authorization_confirmed: str = Form(""),
):
    user = current_user(request)
    if not user:
        return RedirectResponse("/login", status_code=303)
    if not csrf_valid(request, csrf) or authorization_confirmed != "yes":
        return RedirectResponse(f"/projects/{public_id}/performance", status_code=303)
    parsed, _ = validate_target_url(target_url)
    if parsed.query:
        raise ValueError("Performance base URL cannot contain a query string.")
    clean_target = parsed.geturl().rstrip("/")
    config = K6Config(vus, duration_seconds, timeout_seconds).validated()
    with Session(engine) as db:
        project = _owned_project(db, public_id, user.id)
        if not project:
            return RedirectResponse("/projects", status_code=303)
        routes = db.execute(text("""
            SELECT DISTINCT http_method AS method, endpoint_path AS path
            FROM api_inventory WHERE project_id = :project_id AND owner_user_id = :owner
            ORDER BY method, path
        """), {"project_id": project["id"], "owner": user.id}).mappings().all()
        artifact = generate_k6_script(routes, config)
        run, _ = enqueue_performance_run(db, project_id=project["id"], owner_user_id=user.id,
            configuration={"target_url": clean_target, **artifact.configuration, "authorization_confirmed": True},
            defer_commit=True)
        db.add(PerformanceTestArtifact(
            test_run_id=run.id, project_id=project["id"], owner_user_id=user.id,
            target_url=clean_target, authorization_confirmed_at=utc_now(),
            authorization_confirmed_by=user.id, generator_version=GENERATOR_VERSION,
            script_sha256=artifact.sha256, script_text=artifact.script,
            configuration_json=artifact.configuration, metric_map_json=artifact.metric_map,
        ))
        db.commit()
    return RedirectResponse(f"/projects/{public_id}/performance", status_code=303)


@router.post("/projects/{public_id}/performance/{run_id}/cancel")
def cancel_performance_test(request: Request, public_id: str, run_id: int, csrf: str = Form(...)):
    user = current_user(request)
    if not user:
        return RedirectResponse("/login", status_code=303)
    if csrf_valid(request, csrf):
        with Session(engine) as db:
            project = _owned_project(db, public_id, user.id)
            if project:
                request_run_cancellation(db, run_id=run_id, owner_user_id=user.id)
    return RedirectResponse(f"/projects/{public_id}/performance", status_code=303)
