"""Deterministic k6 generation, isolated execution, and exact metrics parsing."""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Iterable

GENERATOR_VERSION = "1.0"
MAX_SUMMARY_BYTES = 20 * 1024 * 1024
SAFE_METHODS = frozenset({"GET", "HEAD"})
PARAMETER = re.compile(r"(?:\{[^{}]+\}|:[A-Za-z_][A-Za-z0-9_]*)")


@dataclass(frozen=True, slots=True)
class K6Config:
    vus: int = 1
    duration_seconds: int = 10
    timeout_seconds: int = 60

    def validated(self) -> "K6Config":
        if not 1 <= int(self.vus) <= 1000:
            raise ValueError("Virtual users must be between 1 and 1000.")
        if not 1 <= int(self.duration_seconds) <= 86400:
            raise ValueError("Duration must be between 1 and 86400 seconds.")
        if not int(self.duration_seconds) <= int(self.timeout_seconds) <= 90000:
            raise ValueError("Timeout must be at least the duration and no more than 90000 seconds.")
        return self


@dataclass(frozen=True, slots=True)
class K6Artifact:
    script: str
    sha256: str
    configuration: dict
    metric_map: dict[str, dict[str, str]]
    skipped_routes: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class K6Execution:
    status: str
    tool_version: str
    summary: dict
    error_message: str | None = None


def k6_available() -> bool:
    return shutil.which("k6") is not None


def _route_parts(route) -> tuple[str, str]:
    if isinstance(route, dict):
        return str(route.get("method") or route.get("http_method") or ""), str(
            route.get("path") or route.get("endpoint_path") or ""
        )
    return str(route.method), str(route.path)


def generate_k6_script(routes: Iterable, config: K6Config = K6Config()) -> K6Artifact:
    """Create a reproducible, read-only-by-default k6 program from canonical routes."""
    config.validated()
    selected: dict[tuple[str, str], None] = {}
    skipped: list[str] = []
    for route in routes:
        method, path = _route_parts(route)
        method, path = method.strip().upper(), path.strip()
        label = f"{method} {path}"
        if method not in SAFE_METHODS or not path.startswith("/") or "\x00" in path:
            skipped.append(label)
            continue
        if PARAMETER.search(path):
            skipped.append(label)
            continue
        selected[(method, path)] = None
    if not selected:
        raise ValueError("No safe, parameter-free GET or HEAD routes are available for load testing.")

    metric_map: dict[str, dict[str, str]] = {}
    declarations, calls = [], []
    for method, path in sorted(selected):
        key = hashlib.sha256(f"{method} {path}".encode()).hexdigest()[:12]
        duration_name, failure_name = f"endpoint_duration_{key}", f"endpoint_failed_{key}"
        metric_map[key] = {
            "method": method, "path": path,
            "duration_metric": duration_name, "failure_metric": failure_name,
        }
        declarations.extend([
            f"const duration_{key} = new Trend({json.dumps(duration_name)});",
            f"const failed_{key} = new Rate({json.dumps(failure_name)});",
        ])
        calls.extend([
            f"  response = http.request({json.dumps(method)}, baseUrl + {json.dumps(path)}, null, requestOptions);",
            f"  duration_{key}.add(response.timings.duration);",
            f"  failed_{key}.add(response.status < 200 || response.status >= 400);",
        ])

    script = "\n".join([
        "// Generated by QAFox. Edit configuration in the UI; secrets are never embedded.",
        "import http from 'k6/http';",
        "import { Trend, Rate } from 'k6/metrics';",
        "",
        *declarations,
        "",
        "export const options = " + json.dumps({
            "vus": config.vus, "duration": f"{config.duration_seconds}s"
        }, sort_keys=True) + ";",
        "",
        "export default function () {",
        "  const baseUrl = (__ENV.BASE_URL || '').replace(/\\/$/, '');",
        "  if (!baseUrl) { throw new Error('BASE_URL is required'); }",
        "  const requestOptions = { redirects: 0, tags: { source: 'qafox' } };",
        "  let response;",
        *calls,
        "}",
        "",
    ])
    digest = hashlib.sha256(script.encode("utf-8")).hexdigest()
    return K6Artifact(
        script, digest,
        {"vus": config.vus, "duration_seconds": config.duration_seconds,
         "timeout_seconds": config.timeout_seconds, "safe_methods": sorted(SAFE_METHODS)},
        metric_map, tuple(sorted(skipped)),
    )


def _number(metric: dict, key: str, default: float = 0.0) -> float:
    try:
        return float((metric.get("values") or {}).get(key, default) or default)
    except (TypeError, ValueError):
        return default


def _duration(metric: dict) -> dict[str, float]:
    return {
        "duration_avg_ms": _number(metric, "avg"),
        "duration_min_ms": _number(metric, "min"),
        "duration_max_ms": _number(metric, "max"),
        "duration_p50_ms": _number(metric, "med"),
        "duration_p90_ms": _number(metric, "p(90)"),
        "duration_p95_ms": _number(metric, "p(95)"),
        "duration_p99_ms": _number(metric, "p(99)"),
    }


def parse_k6_summary(summary: dict, metric_map: dict[str, dict[str, str]]) -> tuple[dict, list[dict]]:
    """Parse k6 summary-export JSON without estimation or AI interpretation."""
    metrics = summary.get("metrics") if isinstance(summary, dict) else None
    if not isinstance(metrics, dict):
        raise ValueError("k6 summary does not contain a metrics object.")
    requests_metric = metrics.get("http_reqs") or {}
    failed_metric = metrics.get("http_req_failed") or {}
    requests = int(_number(requests_metric, "count"))
    failures = int(_number(failed_metric, "fails"))
    error_rate = _number(failed_metric, "rate")
    if not failures and requests and error_rate:
        failures = round(requests * error_rate)
    overall = {
        "requests": requests, "errors": failures, "error_rate": error_rate,
        "requests_per_second": _number(requests_metric, "rate"),
        **_duration(metrics.get("http_req_duration") or {}),
        "data_received_bytes": int(_number(metrics.get("data_received") or {}, "count")),
        "data_sent_bytes": int(_number(metrics.get("data_sent") or {}, "count")),
        "vus_max": int(_number(metrics.get("vus_max") or {}, "max")),
    }
    endpoints = []
    for key in sorted(metric_map):
        mapping = metric_map[key]
        duration = metrics.get(mapping["duration_metric"]) or {}
        failed = metrics.get(mapping["failure_metric"]) or {}
        endpoint_requests = int(_number(duration, "count"))
        endpoint_rate = _number(failed, "rate")
        endpoint_errors = int(_number(failed, "fails"))
        if not endpoint_errors and endpoint_requests and endpoint_rate:
            endpoint_errors = round(endpoint_requests * endpoint_rate)
        endpoints.append({
            "method": mapping["method"], "path": mapping["path"],
            "requests": endpoint_requests, "errors": endpoint_errors,
            "error_rate": endpoint_rate, **_duration(duration),
        })
    return overall, endpoints


def execute_k6(
    script_path: Path, summary_path: Path, *, base_url: str, timeout_seconds: int,
    should_cancel: Callable[[], bool] = lambda: False,
) -> K6Execution:
    binary = shutil.which("k6")
    if not binary:
        return K6Execution("UNAVAILABLE", "not installed", {}, "k6 is not installed on this worker.")
    version = subprocess.run(
        [binary, "version"], capture_output=True, text=True, timeout=10,
        env={"PATH": os.environ.get("PATH", "")}, check=False,
    ).stdout.strip()[:100] or "unknown"
    env = {"PATH": os.environ.get("PATH", ""), "BASE_URL": base_url}
    process = subprocess.Popen(
        [binary, "run", "--quiet", "--summary-export", str(summary_path), str(script_path)],
        cwd=str(script_path.parent), env=env, stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, text=True, shell=False,
    )
    deadline = time.monotonic() + timeout_seconds
    status = "COMPLETED"
    while process.poll() is None:
        if should_cancel():
            status = "CANCELLED"
            process.terminate()
            break
        if time.monotonic() >= deadline:
            status = "FAILED"
            process.terminate()
            break
        time.sleep(0.2)
    try:
        process.communicate(timeout=5)
    except subprocess.TimeoutExpired:
        process.kill()
        process.communicate()
    if status == "CANCELLED":
        return K6Execution(status, version, {}, "Performance run was cancelled.")
    if time.monotonic() >= deadline and status == "FAILED":
        return K6Execution(status, version, {}, "k6 exceeded its configured timeout.")
    if process.returncode:
        return K6Execution("FAILED", version, {}, f"k6 exited with status {process.returncode}.")
    if not summary_path.is_file() or summary_path.stat().st_size > MAX_SUMMARY_BYTES:
        return K6Execution("FAILED", version, {}, "k6 summary is missing or exceeds the size limit.")
    try:
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        return K6Execution("FAILED", version, {}, "k6 produced an invalid summary.")
    return K6Execution("COMPLETED", version, summary)
