"""Project-agnostic smart-data domain and adapter extension points."""

from app.smart_data.adapters import AdapterRegistry, FrameworkAdapter, default_registry
from app.smart_data.capabilities import ADAPTER_CAPABILITY_MATRIX, capabilities_for, capability_matrix
from app.smart_data.contracts import (
    AuthFlowContract,
    ConstraintContract,
    DetectionResult,
    FieldContract,
    PrerequisiteContract,
    RouteContract,
    RuntimeVariableContract,
    SchemaContract,
    SourceEvidence,
    TestDataSource,
    WorkflowActionContract,
)
from app.smart_data.dependency_graph import (
    DependencyGraphBuilder,
    TestDependencyGraph,
)
from app.smart_data.persistence import (
    PersistenceIsolationError,
    persist_contracts,
    load_snapshot,
)
from app.smart_data.uapi import (
    UAPI_CONTRACT_VERSION,
    AdapterCapability,
    ApiContract,
    AssertionContract,
    AuthenticationContract,
    DependencyContract,
    Evidence,
    OperationContract,
    ParameterContract,
    ParameterLocation,
    ProtocolKind,
    RequestContract,
    ResponseContract,
    RuntimeBindingContract,
    SecurityRequirement,
    UniversalContractNormalizer,
)

__all__ = [
    "ADAPTER_CAPABILITY_MATRIX",
    "AdapterCapability",
    "AdapterRegistry",
    "ApiContract",
    "AssertionContract",
    "AuthenticationContract",
    "PersistenceIsolationError",
    "AuthFlowContract",
    "ConstraintContract",
    "DetectionResult",
    "default_registry",
    "DependencyContract",
    "DependencyGraphBuilder",
    "Evidence",
    "FieldContract",
    "FrameworkAdapter",
    "load_snapshot",
    "OperationContract",
    "ParameterContract",
    "ParameterLocation",
    "persist_contracts",
    "PrerequisiteContract",
    "ProtocolKind",
    "RequestContract",
    "ResponseContract",
    "RouteContract",
    "RuntimeBindingContract",
    "RuntimeVariableContract",
    "SchemaContract",
    "SecurityRequirement",
    "SourceEvidence",
    "TestDataSource",
    "TestDependencyGraph",
    "UAPI_CONTRACT_VERSION",
    "UniversalContractNormalizer",
    "WorkflowActionContract",
    "capabilities_for",
    "capability_matrix",
]
